import type { L10n } from "../data/types";

/** UI strings. Placeholders use {name}. Uzbek is the default language. */
export const DICT: Record<string, L10n> = {
  // ---- general
  tagline: { uz: "Maktab hayoti — bitta platformada", ru: "Вся школьная жизнь — на одной платформе", en: "The whole school life in one platform" },
  enter: { uz: "Kirish", ru: "Войти", en: "Sign in" },
  demo_title: { uz: "Demo rejim.", ru: "Демо-режим.", en: "Demo mode." },
  demo_text: { uz: "Bu prototip “{school}” namunaviy ma'lumotlari bilan ishlaydi. Istalgan rolni tanlang — hamma narsa shu brauzerda saqlanadi.", ru: "Прототип работает на примерных данных школы «{school}». Выберите любую роль — всё хранится в этом браузере.", en: "This prototype runs on sample data for “{school}”. Pick any role — everything is stored in this browser." },
  login_footer: { uz: "Ishlab chiqarish versiyasida OneID orqali kirish va ma'lumotlarni O'zbekistondagi serverlarda saqlash rejalashtirilgan.", ru: "В рабочей версии — вход через OneID и хранение данных на серверах в Узбекистане.", en: "The production version will use OneID sign-in and store data on servers in Uzbekistan." },
  role_director: { uz: "Direktor", ru: "Директор", en: "Director" },
  role_teacher: { uz: "O'qituvchi", ru: "Учитель", en: "Teacher" },
  role_student: { uz: "O'quvchi", ru: "Ученик", en: "Student" },
  role_parent: { uz: "Ota-ona", ru: "Родитель", en: "Parent" },
  role_director_desc: { uz: "Maktab paneli, davomat, darvoza skaneri, xavf ostidagi o'quvchilar.", ru: "Панель школы, посещаемость, сканер на входе, ученики в зоне риска.", en: "School dashboard, attendance, entrance scanner, students at risk." },
  role_teacher_desc: { uz: "Jurnal, AI imtihon tekshiruvi, “kimdan so'rash”, dars studiyasi, haftalik testlar.", ru: "Журнал, AI-проверка работ, «кого спросить», студия уроков, еженедельные тесты.", en: "Gradebook, AI exam checking, who to ask first, lesson studio, weekly tests." },
  role_student_desc: { uz: "Kundalik, baholar, haftalik testlar, virtual laboratoriya va AI repetitor.", ru: "Дневник, оценки, еженедельные тесты, виртуальная лаборатория и AI-репетитор.", en: "Diary, grades, weekly tests, virtual lab and an AI tutor." },
  role_parent_desc: { uz: "Farzand maktabga kelgani-ketganini jonli kuzatish, sababli kelmaslikni xabar qilish, baholar.", ru: "Живые уведомления о приходе и уходе ребёнка, сообщение об отсутствии, оценки.", en: "Live arrival and leaving alerts, reporting absences, grades." },
  parent: { uz: "Ota-ona", ru: "Родитель", en: "Parent" },
  hello: { uz: "Salom, {name}!", ru: "Здравствуйте, {name}!", en: "Hello, {name}!" },
  new: { uz: "YANGI", ru: "НОВОЕ", en: "NEW" },
  menu: { uz: "Menyu", ru: "Меню", en: "Menu" },
  language: { uz: "Til", ru: "Язык", en: "Language" },
  theme: { uz: "Mavzu (rang)", ru: "Тема", en: "Theme" },
  light: { uz: "Yorug'", ru: "Светлая", en: "Light" },
  dark: { uz: "Qorong'i", ru: "Тёмная", en: "Dark" },
  close: { uz: "Yopish", ru: "Закрыть", en: "Close" },
  save: { uz: "Saqlash", ru: "Сохранить", en: "Save" },
  saved: { uz: "Saqlandi", ru: "Сохранено", en: "Saved" },
  delete: { uz: "O'chirish", ru: "Удалить", en: "Delete" },
  all: { uz: "Barchasi", ru: "Все", en: "All" },
  open: { uz: "Ochiq", ru: "Открыт", en: "Open" },
  closed: { uz: "Yopilgan", ru: "Закрыт", en: "Closed" },
  back: { uz: "Orqaga", ru: "Назад", en: "Back" },
  send: { uz: "Yuborish", ru: "Отправить", en: "Send" },
  show: { uz: "Ko'rsatish", ru: "Показать", en: "Show" },
  start: { uz: "Boshlash", ru: "Начать", en: "Start" },
  stop: { uz: "To'xtatish", ru: "Стоп", en: "Stop" },
  generate: { uz: "Yaratish", ru: "Создать", en: "Generate" },
  thinking: { uz: "AI o'ylayapti…", ru: "AI думает…", en: "AI is thinking…" },
  today: { uz: "Bugun", ru: "Сегодня", en: "Today" },
  now: { uz: "Hozir", ru: "Сейчас", en: "Now" },
  date: { uz: "Sana", ru: "Дата", en: "Date" },
  time: { uz: "Vaqt", ru: "Время", en: "Time" },
  min: { uz: "daq", ru: "мин", en: "min" },
  not_found: { uz: "Topilmadi", ru: "Не найдено", en: "Not found" },
  notifications: { uz: "Bildirishnomalar", ru: "Уведомления", en: "Notifications" },
  no_notifications: { uz: "Hozircha bildirishnoma yo'q", ru: "Пока нет уведомлений", en: "No notifications yet" },
  mark_read: { uz: "Hammasini o'qildi deb belgilash", ru: "Отметить всё прочитанным", en: "Mark all read" },
  switch_account: { uz: "Rolni almashtirish", ru: "Сменить роль", en: "Switch role" },
  student: { uz: "O'quvchi", ru: "Ученик", en: "Student" },
  students: { uz: "O'quvchilar", ru: "Ученики", en: "Students" },
  subject: { uz: "Fan", ru: "Предмет", en: "Subject" },
  lesson: { uz: "dars", ru: "урок", en: "lesson" },
  lessons: { uz: "Darslar", ru: "Уроки", en: "Lessons" },
  room: { uz: "xona", ru: "каб.", en: "room" },
  topic: { uz: "Mavzu", ru: "Тема", en: "Topic" },
  homework: { uz: "Uy vazifasi", ru: "Домашнее задание", en: "Homework" },
  grade: { uz: "Baho", ru: "Оценка", en: "Grade" },
  grades: { uz: "Baholar", ru: "Оценки", en: "Grades" },
  average: { uz: "O'rtacha", ru: "Средний", en: "Average" },
  trend: { uz: "Tendensiya", ru: "Динамика", en: "Trend" },
  forecast: { uz: "Prognoz", ru: "Прогноз", en: "Forecast" },
  up: { uz: "O'smoqda", ru: "Растёт", en: "Rising" },
  down: { uz: "Pasaymoqda", ru: "Падает", en: "Falling" },
  stable: { uz: "Barqaror", ru: "Стабильно", en: "Stable" },
  done: { uz: "Bajarildi", ru: "Сделано", en: "Done" },
  not_done: { uz: "Bajarilmagan", ru: "Не сделано", en: "Not done" },
  total: { uz: "Jami", ru: "Итого", en: "Total" },
  points: { uz: "Ball", ru: "Баллы", en: "Points" },
  question: { uz: "Savol", ru: "Вопрос", en: "Question" },
  answer: { uz: "Javob", ru: "Ответ", en: "Answer" },
  accept: { uz: "Qabul qilish", ru: "Принять", en: "Accept" },
  until: { uz: "soat", ru: "до", en: "until" },
  grade_word: { uz: "sinf", ru: "класс", en: "grade" },
  all_good: { uz: "Hammasi yaxshi", ru: "Всё хорошо", en: "All good" },
  alerts: { uz: "Ogohlantirishlar", ru: "Оповещения", en: "Alerts" },
  no_alerts: { uz: "Ogohlantirishlar yo'q", ru: "Оповещений нет", en: "No alerts" },

  // ---- navigation
  nav_dashboard: { uz: "Bosh sahifa", ru: "Главная", en: "Dashboard" },
  nav_diary: { uz: "Kundalik", ru: "Дневник", en: "Diary" },
  nav_grades: { uz: "Baholar", ru: "Оценки", en: "Grades" },
  nav_attendance: { uz: "Davomat", ru: "Посещаемость", en: "Attendance" },
  nav_attendance_live: { uz: "Davomat (jonli)", ru: "Посещаемость (live)", en: "Live attendance" },
  nav_gate: { uz: "Darvoza skaneri", ru: "Сканер на входе", en: "Entrance scanner" },
  nav_gradebook: { uz: "Elektron jurnal", ru: "Электронный журнал", en: "Gradebook" },
  nav_askfirst: { uz: "Kimdan so'rash", ru: "Кого спросить", en: "Who to ask first" },
  nav_examcheck: { uz: "AI imtihon tekshiruvi", ru: "AI-проверка работ", en: "AI exam checking" },
  nav_studio: { uz: "AI dars studiyasi", ru: "AI-студия уроков", en: "AI lesson studio" },
  nav_tests: { uz: "Haftalik testlar", ru: "Еженедельные тесты", en: "Weekly tests" },
  nav_lab: { uz: "Virtual laboratoriya", ru: "Виртуальная лаборатория", en: "Virtual lab" },
  nav_assistant: { uz: "AI yordamchi", ru: "AI-помощник", en: "AI assistant" },
  nav_tutor: { uz: "AI repetitor", ru: "AI-репетитор", en: "AI tutor" },
  nav_settings: { uz: "Sozlamalar", ru: "Настройки", en: "Settings" },
  nav_sec_attendance: { uz: "Davomat", ru: "Посещаемость", en: "Attendance" },
  nav_sec_learning: { uz: "O'qish", ru: "Учёба", en: "Learning" },
  nav_sec_ai: { uz: "Sun'iy intellekt", ru: "Искусственный интеллект", en: "AI" },
  nav_sec_ai_teacher: { uz: "AI yordamchi", ru: "AI-помощник", en: "AI assistant" },
  nav_sec_class: { uz: "Sinf", ru: "Класс", en: "Class" },

  // ---- dashboards
  avg_grade: { uz: "O'rtacha baho", ru: "Средний балл", en: "Average grade" },
  attendance: { uz: "Davomat", ru: "Посещаемость", en: "Attendance" },
  attendance_30: { uz: "Davomat (30 kun)", ru: "Посещаемость (30 дней)", en: "Attendance (30 days)" },
  homework_done: { uz: "Uy vazifalari", ru: "Домашние задания", en: "Homework done" },
  open_tests: { uz: "Ochiq testlar", ru: "Открытые тесты", en: "Open tests" },
  late_n: { uz: "{n} marta kechikkan", ru: "опозданий: {n}", en: "{n} late" },
  skipped_n: { uz: "{n} dars qoldirilgan", ru: "пропущено уроков: {n}", en: "{n} lessons skipped" },
  absent_days_n: { uz: "{n} kun kelmagan", ru: "{n} дн. отсутствия", en: "{n} days absent" },
  student_ai_tip: { uz: "AI maslahati: {subject} fanidan o'rtacha bahoingiz {avg}. Repetitor bilan 15 daqiqa mashq qilib ko'ring.", ru: "Совет AI: средний балл по предмету «{subject}» — {avg}. Попробуйте 15 минут позаниматься с репетитором.", en: "AI tip: your average in {subject} is {avg}. Try 15 minutes of practice with the tutor." },
  open_tutor: { uz: "Repetitorni ochish", ru: "Открыть репетитора", en: "Open tutor" },
  today_lessons: { uz: "Bugungi darslar", ru: "Уроки сегодня", en: "Today's lessons" },
  no_lessons_today: { uz: "Bugun dars yo'q", ru: "Сегодня уроков нет", en: "No lessons today" },
  weekly_tests: { uz: "Haftalik testlar", ru: "Еженедельные тесты", en: "Weekly tests" },
  no_open_tests: { uz: "Ochiq test yo'q", ru: "Открытых тестов нет", en: "No open tests" },
  questions_n: { uz: "{n} ta savol", ru: "{n} вопросов", en: "{n} questions" },
  recent_grades: { uz: "So'nggi baholar", ru: "Последние оценки", en: "Recent grades" },
  no_grades: { uz: "Hali baho yo'q", ru: "Оценок пока нет", en: "No grades yet" },
  subject_averages: { uz: "Fanlar bo'yicha o'rtacha", ru: "Средний балл по предметам", en: "Average by subject" },
  parent_sub: { uz: "{name} · {cls}", ru: "{name} · {cls}", en: "{name} · {cls}" },
  today_at_school: { uz: "Bugun maktabda", ru: "Сегодня в школе", en: "Today at school" },
  report_absence: { uz: "Kelmasligini xabar qilish", ru: "Сообщить об отсутствии", en: "Report an absence" },
  alerts_via: { uz: "Xabarlar", ru: "Уведомления через", en: "Alerts via" },
  ch_app: { uz: "Ilova", ru: "Приложение", en: "App" },
  ai_risk: { uz: "AI xavf bahosi", ru: "AI-оценка риска", en: "AI risk check" },
  risk_high: { uz: "Yuqori", ru: "Высокий", en: "High" },
  risk_medium: { uz: "O'rta", ru: "Средний", en: "Medium" },
  risk_low: { uz: "Past", ru: "Низкий", en: "Low" },
  riskr_lowAvg: { uz: "o'rtacha {v}", ru: "средний {v}", en: "average {v}" },
  riskr_falling: { uz: "baholar pasaymoqda", ru: "оценки снижаются", en: "grades falling" },
  riskr_absences: { uz: "{v} kun kelmagan", ru: "{v} дн. пропусков", en: "{v} days absent" },
  riskr_skipped: { uz: "{v} dars qoldirgan", ru: "прогулы: {v}", en: "{v} skipped lessons" },
  riskr_homework: { uz: "uy vazifasi {v}%", ru: "ДЗ {v}%", en: "homework {v}%" },
  recent_events: { uz: "So'nggi voqealar", ru: "Последние события", en: "Recent events" },
  lessons_today: { uz: "Bugungi darslar", ru: "Уроков сегодня", en: "Lessons today" },
  absence_requests: { uz: "Sababli kelmaslik so'rovlari", ru: "Заявки об отсутствии", en: "Absence requests" },
  tests_to_review: { uz: "Tekshiriladigan testlar", ru: "Тесты на проверку", en: "Tests to review" },
  students_at_risk: { uz: "Xavf ostida", ru: "В зоне риска", en: "At risk" },
  homeroom_of: { uz: "{cls} sinf rahbari", ru: "классный руководитель {cls}", en: "homeroom teacher of {cls}" },
  absence_accepted: { uz: "Qabul qilindi, ota-onaga xabar yuborildi", ru: "Принято, родителю отправлено уведомление", en: "Accepted — the parent has been notified" },
  tests_review_alert: { uz: "{n} ta test natijasi mustaqillik bo'yicha tekshirishni talab qiladi", ru: "{n} результатов теста требуют проверки на самостоятельность", en: "{n} test results need an independent-work review" },
  ai_watchlist: { uz: "AI kuzatuv ro'yxati", ru: "AI: список внимания", en: "AI watchlist" },
  ai_watchlist_sub: { uz: "{cls} — e'tibor kerak bo'lgan o'quvchilar (taklif, yakuniy qaror sizda)", ru: "{cls} — ученики, которым нужно внимание (подсказка, решение за вами)", en: "{cls} — students who may need attention (a suggestion; you decide)" },
  ai_watchlist_school: { uz: "Butun maktab bo'yicha yuqori xavf", ru: "Высокий риск по всей школе", en: "High risk across the school" },
  director_sub: { uz: "Bugungi holat va AI tahlili", ru: "Ситуация сегодня и AI-анализ", en: "Today's picture and AI analysis" },
  classes_n: { uz: "{n} ta sinf", ru: "{n} класса", en: "{n} classes" },
  at_school_now: { uz: "Hozir maktabda", ru: "Сейчас в школе", en: "At school now" },
  late_today_n: { uz: "bugun {n} kechikkan", ru: "опоздали сегодня: {n}", en: "{n} late today" },
  school_avg: { uz: "Maktab o'rtachasi", ru: "Средний по школе", en: "School average" },
  attendance_by_class: { uz: "Sinflar bo'yicha davomat", ru: "Посещаемость по классам", en: "Attendance by class" },

  // ---- live status
  status_notArrived: { uz: "Hali maktabga kelmagan", ru: "Ещё не пришёл в школу", en: "Not at school yet" },
  status_atSchool: { uz: "Maktabda ✅ ({in} da kelgan)", ru: "В школе ✅ (пришёл в {in})", en: "At school ✅ (arrived {in})" },
  status_late: { uz: "Maktabda, lekin kechikdi ({in})", ru: "В школе, но опоздал ({in})", en: "At school, arrived late ({in})" },
  status_left: { uz: "Maktabdan chiqdi ({out})", ru: "Ушёл из школы ({out})", en: "Left school ({out})" },
  status_reported: { uz: "Bugun kelmaydi (ota-ona xabar bergan)", ru: "Сегодня отсутствует (сообщил родитель)", en: "Absent today (reported by parent)" },
  status_dayoff: { uz: "Bugun dam olish kuni", ru: "Сегодня выходной", en: "Day off today" },
  status_ok: { uz: "Mustaqil", ru: "Самостоятельно", en: "Independent" },
  status_check: { uz: "Ko'rib chiqing", ru: "Проверить", en: "Check" },
  status_review: { uz: "Tekshirish kerak", ru: "Нужна проверка", en: "Needs review" },
  arrived_at: { uz: "Kelgan: {time}", ru: "Пришёл: {time}", en: "Arrived: {time}" },
  left_at: { uz: "Ketgan: {time}", ru: "Ушёл: {time}", en: "Left: {time}" },

  // ---- notifications
  notif_arrived: { uz: "✅ {student} maktabga keldi — {time}", ru: "✅ {student} пришёл в школу — {time}", en: "✅ {student} arrived at school at {time}" },
  notif_late: { uz: "⏰ {student} maktabga kechikib keldi — {time}", ru: "⏰ {student} опоздал в школу — {time}", en: "⏰ {student} arrived late at {time}" },
  notif_left: { uz: "🏠 {student} maktabdan chiqdi — {time}", ru: "🏠 {student} ушёл из школы — {time}", en: "🏠 {student} left school at {time}" },
  notif_notArrived: { uz: "⚠️ {student} darslar boshlangan bo'lsa ham maktabga kelmadi ({date})", ru: "⚠️ {student} не пришёл в школу, хотя уроки начались ({date})", en: "⚠️ {student} has not arrived although lessons have started ({date})" },
  notif_skipped: { uz: "🚩 {student} maktabda edi, lekin {period}-dars ({subject}) da qatnashmadi — {date}", ru: "🚩 {student} был в школе, но пропустил {period}-й урок ({subject}) — {date}", en: "🚩 {student} was at school but missed lesson {period} ({subject}) on {date}" },
  notif_grade: { uz: "⭐ {student}: {subject} fanidan {value} baho ({date})", ru: "⭐ {student}: оценка {value} по предмету «{subject}» ({date})", en: "⭐ {student} got a {value} in {subject} ({date})" },
  notif_absenceReported: { uz: "📩 Ota-ona xabari: {student} {date} kuni kelmaydi — {reason}", ru: "📩 Родитель сообщил: {student} отсутствует {date} — {reason}", en: "📩 Parent reported: {student} will be absent on {date} — {reason}" },
  notif_absenceAccepted: { uz: "✔️ {student} ning {date} kungi sababi qabul qilindi", ru: "✔️ Причина отсутствия {student} ({date}) принята", en: "✔️ The absence of {student} on {date} was accepted" },
  notif_testFlag: { uz: "🛡 Test natijasi tekshirishni talab qiladi: {student}", ru: "🛡 Результат теста требует проверки: {student}", en: "🛡 A test result needs review: {student}" },

  // ---- grade kinds and marks
  kind_oral: { uz: "Og'zaki", ru: "Устно", en: "Oral" },
  kind_written: { uz: "Yozma", ru: "Письменно", en: "Written" },
  kind_test: { uz: "Test", ru: "Тест", en: "Test" },
  kind_homework: { uz: "Uy vazifasi", ru: "Домашнее задание", en: "Homework" },
  kind_weekly: { uz: "Haftalik test", ru: "Еженедельный тест", en: "Weekly test" },
  kind_exam: { uz: "Nazorat ishi", ru: "Контрольная", en: "Exam" },
  mark_absent: { uz: "Kelmagan", ru: "Отсутствовал", en: "Absent" },
  mark_late: { uz: "Kechikkan", ru: "Опоздал", en: "Late" },
  mark_excused: { uz: "Sababli", ru: "По уважительной", en: "Excused" },
  mark_present_short: { uz: "Bor", ru: "Есть", en: "In" },
  mark_late_short: { uz: "Kech", ru: "Опозд.", en: "Late" },
  mark_absent_short: { uz: "Yo'q", ru: "Нет", en: "Absent" },
  mark_excused_short: { uz: "Sababli", ru: "Уваж.", en: "Excused" },
  reason_sick: { uz: "Kasal", ru: "Болезнь", en: "Sick" },
  reason_doctor: { uz: "Shifokor qabulida", ru: "У врача", en: "Doctor's appointment" },
  reason_family: { uz: "Oilaviy sabab", ru: "Семейные обстоятельства", en: "Family reasons" },
  reason_other: { uz: "Boshqa", ru: "Другое", en: "Other" },
  abs_pending: { uz: "Kutilmoqda", ru: "Ожидает", en: "Pending" },
  abs_accepted: { uz: "Qabul qilindi", ru: "Принято", en: "Accepted" },

  // ---- diary / grades pages
  prev_week: { uz: "Oldingi hafta", ru: "Предыдущая неделя", en: "Previous week" },
  next_week: { uz: "Keyingi hafta", ru: "Следующая неделя", en: "Next week" },
  avg_trend: { uz: "O'rtacha baho dinamikasi", ru: "Динамика среднего балла", en: "Average grade over time" },
  avg_trend_sub: { uz: "Haftalik o'rtacha", ru: "Среднее за неделю", en: "Weekly average" },
  grade_distribution: { uz: "Baholar taqsimoti", ru: "Распределение оценок", en: "Grade distribution" },
  grades_total: { uz: "Jami {n} ta baho", ru: "Всего оценок: {n}", en: "{n} grades in total" },
  by_subject: { uz: "Fanlar bo'yicha", ru: "По предметам", en: "By subject" },
  forecast_explain: { uz: "AI prognozi — oxirgi baholar va tendensiya asosida chorak bahosi taxmini", ru: "Прогноз AI — ожидаемая четвертная оценка по последним оценкам и динамике", en: "AI forecast — the expected quarter grade from recent grades and the trend" },

  // ---- attendance pages
  report_absence_sub: { uz: "Sinf rahbari darhol xabar oladi", ru: "Классный руководитель получит сообщение сразу", en: "The homeroom teacher is notified immediately" },
  reason: { uz: "Sabab", ru: "Причина", en: "Reason" },
  partial_day: { uz: "Faqat bir qismiga kelmaydi (kechroq keladi)", ru: "Придёт позже (частичное отсутствие)", en: "Only part of the day (will come later)" },
  comes_at: { uz: "Soat nechada keladi", ru: "Во сколько придёт", en: "Arrives at" },
  note_optional: { uz: "Izoh (ixtiyoriy)", ru: "Комментарий (необязательно)", en: "Note (optional)" },
  note_ph: { uz: "Masalan: shifokor ma'lumotnomasi ertaga olib boriladi", ru: "Например: справку принесём завтра", en: "e.g. we will bring the doctor's note tomorrow" },
  send_to_teacher: { uz: "Sinf rahbariga yuborish", ru: "Отправить классному руководителю", en: "Send to homeroom teacher" },
  absence_sent: { uz: "Yuborildi! O'qituvchi tasdiqlagach xabar olasiz.", ru: "Отправлено! Вы получите уведомление после подтверждения.", en: "Sent! You'll be notified when the teacher confirms." },
  alert_settings: { uz: "Xabar sozlamalari", ru: "Настройки уведомлений", en: "Alert settings" },
  alert_settings_sub: { uz: "Kelish, ketish va kechikish xabarlari qayerga kelsin", ru: "Куда присылать уведомления о приходе, уходе и опозданиях", en: "Where to receive arrival, leaving and lateness alerts" },
  privacy_note: { uz: "Maxfiylik: biz GPS orqali kuzatmaymiz — faqat maktab darvozasidan kirish va chiqish vaqti qayd etiladi.", ru: "Конфиденциальность: никакого GPS-слежения — фиксируются только вход и выход через школьный турникет.", en: "Privacy: no GPS tracking — only entering and leaving through the school gate is recorded." },
  arrival_log: { uz: "Kelish-ketish jurnali", ru: "Журнал прихода и ухода", en: "Arrival and leaving log" },
  arrival_log_sub: { uz: "So'nggi 3 hafta", ru: "Последние 3 недели", en: "Last 3 weeks" },
  arrival: { uz: "Kelgan", ru: "Пришёл", en: "Arrived" },
  leaving: { uz: "Ketgan", ru: "Ушёл", en: "Left" },
  not_at_school: { uz: "Kelmagan", ru: "Не был", en: "Not at school" },
  all_lessons: { uz: "Barcha {n} darsda", ru: "На всех {n} уроках", en: "All {n} lessons" },
  skipped: { uz: "Qoldirgan", ru: "Прогул", en: "Skipped" },
  lesson_att_hint: { uz: "Darvoza skaneri ma'lumoti yonida ko'rsatiladi. Agar o'quvchi maktabga kirgan bo'lsa-yu, darsda bo'lmasa — ota-onasi va sinf rahbari darhol xabar oladi.", ru: "Рядом показаны данные сканера на входе. Если ученик в школе, но не на уроке — родитель и классный руководитель сразу получат уведомление.", en: "Gate-scan data is shown next to each student. If a student is in the building but not in your lesson, the parent and homeroom teacher are alerted immediately." },
  present_n: { uz: "Darsda: {n} / {total}", ru: "На уроке: {n} из {total}", en: "Present: {n} of {total}" },
  gate_in_at: { uz: "darvozadan {time} da kirgan", ru: "вошёл в {time}", en: "entered at {time}" },
  parent_reported: { uz: "ota-ona xabar bergan: {reason}", ru: "родитель сообщил: {reason}", en: "parent reported: {reason}" },
  no_gate_scan: { uz: "bugun darvozadan o'tmagan", ru: "сегодня не проходил турникет", en: "no gate scan today" },
  notify_missing: { uz: "Kelmaganlarning ota-onasiga xabar", ru: "Уведомить родителей отсутствующих", en: "Notify parents of missing students" },
  missing_notified: { uz: "{n} nafar o'quvchining ota-onasiga xabar yuborildi", ru: "Уведомлены родители {n} учеников", en: "Notified the parents of {n} students" },
  st_atSchool: { uz: "Maktabda", ru: "В школе", en: "At school" },
  st_late: { uz: "Kechikkan", ru: "Опоздал", en: "Late" },
  st_left: { uz: "Ketgan", ru: "Ушли", en: "Left" },
  st_reported: { uz: "Sababli", ru: "По уважительной", en: "Reported" },
  st_notArrived: { uz: "Kelmagan", ru: "Не пришли", en: "Not arrived" },
  class_today: { uz: "Sinf bugun", ru: "Класс сегодня", en: "Class today" },
  skipped_lessons: { uz: "Qoldirilgan darslar", ru: "Прогулы", en: "Skipped lessons" },
  skipped_lessons_sub: { uz: "Maktabda bo'lib, darsda bo'lmaganlar", ru: "Были в школе, но не на уроке", en: "In the building but not in class" },

  // ---- gate
  gate_sub: { uz: "Kirishda QR/NFC kartani skanerlash — ota-onaga darhol xabar boradi", ru: "Сканирование QR/NFC-карты на входе — родитель сразу получает уведомление", en: "Scan the QR/NFC card at the entrance — the parent is notified instantly" },
  simulate_morning: { uz: "Ertalabni simulyatsiya qilish", ru: "Смоделировать утро", en: "Simulate the morning" },
  simulated_n: { uz: "{n} nafar o'quvchi kirdi, ota-onalarga xabar ketdi", ru: "Вошли {n} учеников, родители уведомлены", en: "{n} students checked in and their parents were notified" },
  scanner: { uz: "Skaner", ru: "Сканер", en: "Scanner" },
  scanner_sub: { uz: "Prototipda kartani kod yoki ism bo'yicha tanlang", ru: "В прототипе выберите карту по коду или имени", en: "In the prototype, pick a card by code or name" },
  show_card: { uz: "Kartani ko'rsating", ru: "Покажите карту", en: "Show your card" },
  card_or_name: { uz: "Karta kodi yoki ism", ru: "Код карты или имя", en: "Card code or name" },
  check_in: { uz: "Kirish", ru: "Вход", en: "Check in" },
  check_out: { uz: "Chiqish", ru: "Выход", en: "Check out" },
  checked_in: { uz: "Kirdi", ru: "Вошёл", en: "Checked in" },
  checked_out: { uz: "Chiqdi", ru: "Вышел", en: "Checked out" },
  use_real_time: { uz: "Haqiqiy vaqt", ru: "Текущее время", en: "Use real time" },
  late_after: { uz: "{time} dan keyin — kechikish", ru: "после {time} — опоздание", en: "late after {time}" },
  parent_sees: { uz: "Ota-ona nimani ko'radi", ru: "Что видит родитель", en: "What the parent sees" },
  parent_sees_sub: { uz: "Telegram bot / ilova xabari", ru: "Сообщение в Telegram-боте / приложении", en: "Telegram bot / app message" },
  scan_to_preview: { uz: "Kartani skanerlang — xabar shu yerda ko'rinadi", ru: "Отсканируйте карту — сообщение появится здесь", en: "Scan a card to preview the message" },
  live_feed: { uz: "Jonli lenta", ru: "Лента событий", en: "Live feed" },
  no_scans: { uz: "Bugun hali skanerlash yo'q", ru: "Сегодня ещё нет сканирований", en: "No scans yet today" },
  arrived: { uz: "Keldi", ru: "Пришёл", en: "Arrived" },
  late: { uz: "Kechikdi", ru: "Опоздал", en: "Late" },
  left: { uz: "Ketdi", ru: "Ушёл", en: "Left" },

  // ---- gradebook
  gradebook_sub: { uz: "Ustunni bosing — mavzu va uy vazifasi; katakni bosing — baho", ru: "Нажмите на столбец — тема и ДЗ; на ячейку — оценка", en: "Click a date for topic and homework; click a cell to grade" },
  class_subject: { uz: "Sinf va fan", ru: "Класс и предмет", en: "Class and subject" },
  export_excel: { uz: "Excel'ga eksport", ru: "Экспорт в Excel", en: "Export to Excel" },
  gradebook_hint: { uz: "Binafsha hoshiyali baho — AI taklif qilgan va siz tasdiqlagan baho. “nb” — darsda bo'lmagan.", ru: "Оценка с фиолетовой рамкой — предложена AI и подтверждена вами. «нб» — отсутствовал.", en: "A purple ring marks a grade suggested by AI and approved by you. “nb” means absent." },
  grade_type: { uz: "Baho turi", ru: "Тип оценки", en: "Grade type" },
  comment_optional: { uz: "Izoh (ixtiyoriy)", ru: "Комментарий (необязательно)", en: "Comment (optional)" },
  put_grade: { uz: "Baho qo'yish", ru: "Поставить оценку", en: "Give a grade" },
  ai_suggested_approved: { uz: "AI taklifi, tasdiqlangan", ru: "предложено AI, подтверждено", en: "AI-suggested, approved" },

  // ---- ask first
  askfirst_sub: { uz: "AI darsga tayyor bo'lmasligi mumkin bo'lgan o'quvchilarni ko'rsatadi", ru: "AI показывает, кто, вероятно, не готов к уроку", en: "AI shows who is probably not ready for today's lesson" },
  last_topic: { uz: "oxirgi mavzu", ru: "последняя тема", en: "last topic" },
  askfirst_how: { uz: "Hisobga olinadi: uy vazifasi, oxirgi baholar va dinamika, oldingi darsga kelmagani, haftalik test natijasi va qachon oxirgi marta so'ralgani.", ru: "Учитываются: ДЗ, последние оценки и динамика, пропуск прошлого урока, результат еженедельного теста и когда ученика спрашивали в последний раз.", en: "Based on: homework, recent grades and trend, missing the previous lesson, the weekly test result, and when the student was last asked." },
  ask_first_title: { uz: "Birinchi navbatda so'rang", ru: "Спросить в первую очередь", en: "Ask these first" },
  ask_first_desc: { uz: "Ehtimol tayyor emas", ru: "Вероятно, не готовы", en: "Probably not ready" },
  not_asked_title: { uz: "Uzoq vaqt so'ralmagan", ru: "Давно не спрашивали", en: "Not asked for a while" },
  not_asked_desc: { uz: "Adolatli navbat uchun", ru: "Для справедливой очереди", en: "For a fair rotation" },
  everyone_ready: { uz: "Hamma tayyor ko'rinadi", ru: "Похоже, все готовы", en: "Everyone looks ready" },
  everyone_asked: { uz: "Hamma yaqinda so'ralgan", ru: "Всех недавно спрашивали", en: "Everyone was asked recently" },
  readiness_score: { uz: "xavf {n}", ru: "риск {n}", en: "risk {n}" },
  ready_noHomework: { uz: "uy vazifasi yo'q", ru: "нет ДЗ", en: "no homework" },
  ready_lowRecent: { uz: "oxirgi baholar {avg}", ru: "последние оценки {avg}", en: "recent grades {avg}" },
  ready_dropping: { uz: "baholar pasaymoqda", ru: "оценки снижаются", en: "grades dropping" },
  ready_missedLast: { uz: "{date} darsida yo'q edi", ru: "отсутствовал {date}", en: "missed the {date} lesson" },
  ready_weakTest: { uz: "haftalik test {pct}%", ru: "тест {pct}%", en: "weekly test {pct}%" },
  ready_notAsked: { uz: "{days} kun so'ralmagan", ru: "не спрашивали {days} дн.", en: "not asked for {days} days" },
  asked: { uz: "So'raldi", ru: "Спрошен", en: "Asked" },
  grade_saved_for: { uz: "{name}: {value} baho qo'yildi", ru: "{name}: поставлена {value}", en: "{name}: grade {value} saved" },
  ai_oral_questions: { uz: "Dars boshidagi og'zaki savollar", ru: "Устные вопросы в начале урока", en: "Opening oral questions" },
  ai_oral_questions_sub: { uz: "Bugungi mavzu bo'yicha 6 ta savol va kutilgan javoblar", ru: "6 вопросов по теме и ожидаемые ответы", en: "6 questions on the topic with expected answers" },
  askfirst_privacy: { uz: "Bu ro'yxatni faqat siz ko'rasiz. U o'quvchini jazolash uchun emas, qo'llab-quvvatlash uchun.", ru: "Этот список видите только вы. Он для поддержки учеников, а не для наказания.", en: "Only you see this list. It is for supporting students, not punishing them." },

  // ---- exam check
  examcheck_sub: { uz: "Javoblar varag'i rasmini yuklang — AI o'qiydi, tekshiradi va baho taklif qiladi. Yakuniy qaror sizda.", ru: "Загрузите фото работ — AI прочитает, проверит и предложит оценку. Решение за вами.", en: "Upload photos of answer sheets — AI reads, checks and suggests a grade. You make the final decision." },
  exam_default_title: { uz: "Nazorat ishi", ru: "Контрольная работа", en: "Exam" },
  exam_title: { uz: "Ish nomi", ru: "Название работы", en: "Exam title" },
  answer_key: { uz: "Javoblar kaliti", ru: "Ключ ответов", en: "Answer key" },
  answer_key_sub: { uz: "To'g'ri javob yoki baholash mezoni va ball", ru: "Правильный ответ или критерий и баллы", en: "Correct answer or rubric, and points" },
  correct_answer: { uz: "To'g'ri javob / mezon", ru: "Ответ / критерий", en: "Answer / rubric" },
  add_question: { uz: "Savol qo'shish", ru: "Добавить вопрос", en: "Add question" },
  max_points: { uz: "Maksimal ball", ru: "Максимум баллов", en: "Max points" },
  student_papers: { uz: "O'quvchilar ishlari", ru: "Работы учеников", en: "Student papers" },
  student_papers_sub: { uz: "Rasm yuklang yoki javoblarni kiriting", ru: "Загрузите фото или введите ответы", en: "Upload a photo or type the answers" },
  load_sample: { uz: "Namuna javoblarni yuklash", ru: "Загрузить пример ответов", en: "Load sample answers" },
  check_all: { uz: "AI bilan tekshirish", ru: "Проверить с AI", en: "Check with AI" },
  checking_name: { uz: "Tekshirilmoqda: {name}", ru: "Проверяется: {name}", en: "Checking: {name}" },
  examcheck_offline: { uz: "AI kaliti ulanmagan: yozilgan javoblar oflayn tekshiriladi (raqamlar va ifodalarni solishtirish). Rasmdan o'qish uchun Sozlamalarda AI'ni ulang.", ru: "AI-ключ не подключён: введённые ответы проверяются офлайн (сравнение чисел и выражений). Для чтения фото подключите AI в настройках.", en: "No AI key: typed answers are checked offline by comparing numbers and expressions. Connect AI in Settings to read photos." },
  photo_needs_key: { uz: "Rasmdagi ishlarni o'qish uchun AI kaliti kerak.", ru: "Чтобы читать фото работ, нужен AI-ключ.", en: "Reading photos needs an AI key." },
  photo: { uz: "Rasm", ru: "Фото", en: "Photo" },
  upload_photo: { uz: "Ish rasmini yuklash", ru: "Загрузить фото работы", en: "Upload a photo of the paper" },
  from_photo: { uz: "rasmdan", ru: "с фото", en: "from photo" },
  check_manually: { uz: "Qo'lda tekshiring", ru: "Проверьте вручную", en: "Check by hand" },
  results_approve: { uz: "Natijalar va tasdiqlash", ru: "Результаты и подтверждение", en: "Results and approval" },
  results_approve_sub: { uz: "Ballar va bahoni o'zgartirishingiz mumkin, keyin jurnalga saqlang", ru: "Можно изменить баллы и оценку, затем сохранить в журнал", en: "Adjust points or grades if needed, then save to the gradebook" },
  approve_save: { uz: "Tasdiqlash va jurnalga yozish", ru: "Подтвердить и записать в журнал", en: "Approve and save to gradebook" },
  grades_saved_n: { uz: "{n} ta baho jurnalga yozildi", ru: "В журнал записано оценок: {n}", en: "{n} grades saved to the gradebook" },
  class_average: { uz: "Sinf o'rtachasi", ru: "Средний по классу", en: "Class average" },
  hardest_question: { uz: "Eng qiyin savol", ru: "Самый трудный вопрос", en: "Hardest question" },
  solved_pct: { uz: "{n}% to'g'ri", ru: "{n}% верно", en: "{n}% correct" },
  teacher_decides: { uz: "AI faqat taklif beradi. Har bir baho siz tasdiqlaganingizdan keyingina jurnalga tushadi va audit jurnalida qayd etiladi.", ru: "AI только предлагает. Оценка попадает в журнал лишь после вашего подтверждения.", en: "AI only suggests. A grade reaches the gradebook only after you approve it." },

  // ---- studio
  studio_sub: { uz: "Mavzuni yozing — dars rejasi, virtual tajriba, video ssenariy, test va slaydlar", ru: "Введите тему — план урока, виртуальный опыт, сценарий видео, тест и слайды", en: "Enter a topic — get a lesson plan, virtual experiment, video script, quiz and slides" },
  examples: { uz: "Misollar", ru: "Примеры", en: "Examples" },
  duration: { uz: "Davomiyligi", ru: "Длительность", en: "Length" },
  tab_plan: { uz: "Dars rejasi", ru: "План урока", en: "Lesson plan" },
  tab_lab: { uz: "Virtual tajriba", ru: "Виртуальный опыт", en: "Virtual experiment" },
  tab_video: { uz: "Video", ru: "Видео", en: "Video" },
  tab_experiment: { uz: "Haqiqiy tajriba", ru: "Реальный опыт", en: "Real experiment" },
  tab_quiz: { uz: "Test va topshiriqlar", ru: "Тест и задания", en: "Quiz and worksheet" },
  tab_slides: { uz: "Slaydlar", ru: "Слайды", en: "Slides" },
  plan_sub: { uz: "Milliy o'quv dasturiga mos", ru: "По национальной программе", en: "Aligned to the national curriculum" },
  plan_greet: { uz: "Salomlashish, maqsadni e'lon qilish, motivatsiya savoli", ru: "Приветствие, цель урока, мотивирующий вопрос", en: "Greeting, lesson goal, a motivating question" },
  plan_check_hw: { uz: "Uy vazifasini tekshirish (“Kimdan so'rash” ro'yxati bo'yicha)", ru: "Проверка ДЗ (по списку «Кого спросить»)", en: "Homework check (using the “Who to ask first” list)" },
  plan_new: { uz: "Yangi mavzu tushuntirish, misollar", ru: "Объяснение новой темы, примеры", en: "Explaining the new topic with examples" },
  plan_demo: { uz: "Virtual tajribani namoyish qilish va kuzatishlarni muhokama qilish", ru: "Демонстрация виртуального опыта и обсуждение наблюдений", en: "Showing the virtual experiment and discussing observations" },
  plan_practice: { uz: "Juftlikda mashq qilish", ru: "Практика в парах", en: "Practice in pairs" },
  plan_consolidate: { uz: "Mustahkamlash: 3 ta qisqa savol", ru: "Закрепление: 3 коротких вопроса", en: "Consolidation: 3 short questions" },
  plan_hw: { uz: "Uy vazifasi va baholash", ru: "Домашнее задание и оценивание", en: "Homework and grading" },
  plan_goals: { uz: "Maqsadlar", ru: "Цели", en: "Goals" },
  plan_goal1: { uz: "O'quvchilar “{topic}” mavzusining asosiy tushunchalarini tushuntira oladi", ru: "Ученики могут объяснить ключевые понятия темы «{topic}»", en: "Students can explain the key ideas of “{topic}”" },
  plan_goal2: { uz: "Bilimni masala va savollarda qo'llay oladi", ru: "Применяют знания в задачах и вопросах", en: "Students apply the knowledge to problems and questions" },
  plan_goal3: { uz: "Kuzatish va xulosa chiqarishni mashq qiladi", ru: "Тренируют наблюдение и выводы", en: "Students practise observing and drawing conclusions" },
  plan_steps: { uz: "Dars bosqichlari", ru: "Этапы урока", en: "Lesson steps" },
  plan_resources: { uz: "Resurslar", ru: "Ресурсы", en: "Resources" },
  plan_res_book: { uz: "Darslik va doska", ru: "Учебник и доска", en: "Textbook and board" },
  plan_res_lab: { uz: "Maktab+ virtual laboratoriyasi", ru: "Виртуальная лаборатория Maktab+", en: "Maktab+ virtual lab" },
  plan_res_quiz: { uz: "Maktab+ test generatori", ru: "Генератор тестов Maktab+", en: "Maktab+ quiz generator" },
  lab_sub: { uz: "Interaktiv simulyatsiya — sinfda proyektor orqali ko'rsating", ru: "Интерактивная симуляция — показывайте через проектор", en: "Interactive simulation — show it on the classroom projector" },
  lab_none: { uz: "Bu mavzu uchun tayyor simulyatsiya yo'q — kimyo tajribalaridan birini tanlang", ru: "Для этой темы нет готовой симуляции — выберите опыт по химии", en: "No ready simulation for this topic — pick one of the chemistry experiments" },
  video_title: { uz: "AI video:", ru: "AI-видео:", en: "AI video:" },
  video_text: { uz: "prototipda AI video ssenariy va har bir sahna uchun video-generator so'rovlarini yozadi, animatsion oldindan ko'rish esa virtual laboratoriyadan olinadi. Video yaratish servisi 3-bosqichda ulanadi; har bir video sinfda ko'rsatilishidan oldin o'qituvchi tomonidan tekshiriladi.", ru: "в прототипе AI пишет сценарий и промпты для видеогенератора по сценам, а анимированное превью берётся из виртуальной лаборатории. Сервис генерации видео подключается на этапе 3; каждое видео учитель проверяет перед показом.", en: "in the prototype the AI writes the storyboard and a text-to-video prompt for each scene, and the animated preview comes from the virtual lab. A video-generation service is connected in Phase 3; the teacher previews every video before showing it." },
  video_preview: { uz: "Animatsion oldindan ko'rish", ru: "Анимированное превью", en: "Animated preview" },
  video_preview_sub: { uz: "Sinfda video sifatida ko'rsatish mumkin", ru: "Можно показать в классе как видео", en: "Can be played in class like a video" },
  video_script: { uz: "Video ssenariy (storyboard)", ru: "Сценарий видео (раскадровка)", en: "Video storyboard" },
  video_script_sub: { uz: "Sahnalar, matn va video-generator uchun so'rovlar", ru: "Сцены, текст диктора и промпты для генератора", en: "Scenes, narration and text-to-video prompts" },
  experiment_sub: { uz: "Materiallar, qadamlar va xavfsizlik qoidalari", ru: "Материалы, шаги и правила безопасности", en: "Materials, steps and safety rules" },
  quiz_sub: { uz: "Uch darajadagi savollar va javoblar", ru: "Вопросы трёх уровней с ответами", en: "Three levels of questions with answers" },
  slides_sub: { uz: "8–10 slayd rejasi", ru: "План из 8–10 слайдов", en: "An 8–10 slide outline" },
  quiz: { uz: "Test", ru: "Тест", en: "Quiz" },
  no_bank: { uz: "Bu fan uchun oflayn savollar banki yo'q — AI kalitini ulang", ru: "Для этого предмета нет офлайн-банка вопросов — подключите AI", en: "No offline question bank for this subject — connect an AI key" },

  // ---- lab
  lab_page_sub: { uz: "Xavfli tajribalarni ham xavfsiz kuzating", ru: "Безопасно наблюдайте даже опасные опыты", en: "Watch even dangerous experiments safely" },
  phenolphthalein: { uz: "fenolftalein", ru: "фенолфталеин", en: "phenolphthalein" },
  reaction_done: { uz: "Reaksiya tugadi", ru: "Реакция завершена", en: "Reaction complete" },
  grade_level: { uz: "{g}-sinf", ru: "{g} класс", en: "Grade {g}" },
  start_experiment: { uz: "Tajribani boshlash", ru: "Начать опыт", en: "Start experiment" },
  pause: { uz: "Pauza", ru: "Пауза", en: "Pause" },
  continue: { uz: "Davom etish", ru: "Продолжить", en: "Continue" },
  replay: { uz: "Qayta ko'rish", ru: "Повторить", en: "Replay" },
  reset: { uz: "Qaytadan", ru: "Сброс", en: "Reset" },
  splint_test: { uz: "Yonayotgan cho'p bilan sinash", ru: "Проба горящей лучинкой", en: "Lit-splint test" },
  acid_added: { uz: "Qo'shilgan HCl: {ml} ml", ru: "Добавлено HCl: {ml} мл", en: "HCl added: {ml} mL" },
  add_drop: { uz: "Tomchi qo'shish", ru: "Добавить каплю", en: "Add a drop" },
  observations: { uz: "Kuzatishlar", ru: "Наблюдения", en: "Observations" },
  safety: { uz: "Xavfsizlik", ru: "Безопасность", en: "Safety" },

  // ---- weekly tests
  tests_student_sub: { uz: "Har hafta o'tilgan mavzular bo'yicha qisqa test", ru: "Короткий тест по темам недели", en: "A short test on each week's topics" },
  tests_fair_note: { uz: "Har bir o'quvchida savollar tartibi va variantlar boshqacha. Testdan keyin AI sizdan javobingizni o'z so'zlaringiz bilan tushuntirishni so'raydi.", ru: "У каждого ученика свой порядок вопросов и вариантов. После теста AI попросит объяснить ответ своими словами.", en: "Every student gets a different order of questions and options. After the test the AI asks you to explain one answer in your own words." },
  week_of: { uz: "{date} haftasi", ru: "неделя с {date}", en: "week of {date}" },
  see_answers: { uz: "Javoblarni ko'rish", ru: "Посмотреть ответы", en: "See answers" },
  your_answer: { uz: "Sizning javobingiz", ru: "Ваш ответ", en: "Your answer" },
  correct: { uz: "To'g'ri", ru: "Верно", en: "Correct" },
  wrong: { uz: "Noto'g'ri", ru: "Неверно", en: "Wrong" },
  tests_teacher_sub: { uz: "AI testlarni tuzadi, tekshiradi va mustaqil ishlanganini tahlil qiladi", ru: "AI составляет тесты, проверяет их и анализирует самостоятельность", en: "AI builds the tests, marks them and checks for independent work" },
  create_weekly: { uz: "Haftalik test yaratish", ru: "Создать еженедельный тест", en: "Create weekly test" },
  create_weekly_ai: { uz: "AI shu hafta jurnalga yozilgan mavzular asosida 6 ta savol tuzadi (o'zbek, rus va ingliz tillarida).", ru: "AI составит 6 вопросов по темам этой недели из журнала (на трёх языках).", en: "AI writes 6 questions from this week's topics in the gradebook (in three languages)." },
  create_weekly_offline: { uz: "AI kaliti ulanmagan — savollar oflayn bankdan olinadi.", ru: "AI-ключ не подключён — вопросы берутся из офлайн-банка.", en: "No AI key — questions come from the offline bank." },
  test_created: { uz: "Test yaratildi va o'quvchilarga ochildi", ru: "Тест создан и открыт ученикам", en: "Test created and opened to students" },
  test_closed_n: { uz: "Test yopildi, {n} ta baho jurnalga yozildi", ru: "Тест закрыт, в журнал записано {n} оценок", en: "Test closed, {n} grades saved" },
  tests: { uz: "Testlar", ru: "Тесты", en: "Tests" },
  no_tests: { uz: "Testlar yo'q", ru: "Тестов нет", en: "No tests" },
  done_n: { uz: "{n} ta topshirgan", ru: "сдали: {n}", en: "{n} submitted" },
  close_send_grades: { uz: "Yopish va baholarni yozish", ru: "Закрыть и выставить оценки", en: "Close and send grades" },
  integrity_explain: { uz: "Mustaqillik tekshiruvi: o'xshash javoblar, bir xil xatolar, odatdagidan keskin yuqori natija, juda tez javob, nusxa ko'chirish, oynadan chiqish va AI qo'shimcha savoliga javob. Bu faqat signallar — qaror sizniki. “Tekshirish kerak” natijalar siz qaror qilmaguningizcha jurnalga yozilmaydi.", ru: "Проверка самостоятельности: похожие ответы, одинаковые ошибки, резкий скачок результата, слишком быстрые ответы, вставка текста, уход из окна и ответ на уточняющий вопрос AI. Это только сигналы — решение за вами.", en: "Independent-work check: similar answers, identical mistakes, a sudden jump above the usual level, very fast answers, pasting, leaving the window, and the answer to the AI follow-up question. These are signals only — you decide. Results marked “needs review” are not graded until you do." },
  no_attempts: { uz: "Hali hech kim topshirmagan", ru: "Пока никто не сдал", en: "No submissions yet" },
  not_taken: { uz: "Topshirmagan", ru: "Не сдал", en: "Not taken" },
  integrity_ok: { uz: "Mustaqil ishlagan", ru: "Работал самостоятельно", en: "Worked independently" },
  flag_similar: { uz: "Yozma javob(lar) {other} niki bilan deyarli bir xil ({count})", ru: "Письменные ответы почти совпадают с {other} ({count})", en: "Written answer nearly identical to {other} ({count})" },
  flag_samePattern: { uz: "{other} bilan bir xil xatolar ({wrong})", ru: "Те же ошибки, что у {other} ({wrong})", en: "Same mistakes as {other} ({wrong})" },
  flag_levelJump: { uz: "Natija {pct}%, odatdagi o'rtacha {usual}", ru: "Результат {pct}%, обычно {usual}", en: "Scored {pct}%, usual average {usual}" },
  flag_tooFast: { uz: "{count} savolga juda tez javob", ru: "Слишком быстрые ответы: {count}", en: "{count} answers far too fast" },
  flag_paste: { uz: "Matn joylashtirilgan ({count})", ru: "Вставка текста ({count})", en: "Pasted text ({count})" },
  flag_leftWindow: { uz: "Test oynasidan {count} marta chiqqan", ru: "Покидал окно теста {count} раз", en: "Left the test window {count} times" },
  flag_followUpWeak: { uz: "O'z javobini tushuntira olmadi", ru: "Не смог объяснить свой ответ", en: "Couldn't explain their own answer" },
  followup_answer: { uz: "Qo'shimcha savolga javob", ru: "Ответ на уточняющий вопрос", en: "Follow-up answer" },
  fu_ok: { uz: "tushunadi", ru: "понимает", en: "understands" },
  fu_weak: { uz: "tushuntira olmadi", ru: "не объяснил", en: "couldn't explain" },
  fu_pending: { uz: "javob yo'q", ru: "нет ответа", en: "no answer" },
  independent: { uz: "Mustaqil", ru: "Самостоятельно", en: "Independent" },
  talk_to_student: { uz: "Suhbatlashish kerak", ru: "Поговорить", en: "Talk to student" },
  review_ok: { uz: "O'qituvchi: mustaqil", ru: "Учитель: самостоятельно", en: "Teacher: independent" },
  review_suspicious: { uz: "O'qituvchi: suhbat kerak", ru: "Учитель: нужен разговор", en: "Teacher: needs a talk" },
  already_done: { uz: "Siz bu testni allaqachon topshirgansiz", ru: "Вы уже сдали этот тест", en: "You have already taken this test" },
  question_of: { uz: "{i}-savol / {n}", ru: "вопрос {i} из {n}", en: "question {i} of {n}" },
  diff_1: { uz: "Oson", ru: "Легко", en: "Easy" },
  diff_2: { uz: "O'rta", ru: "Средне", en: "Medium" },
  diff_3: { uz: "Qiyin", ru: "Сложно", en: "Hard" },
  write_answer: { uz: "Javobingizni o'z so'zlaringiz bilan yozing", ru: "Напишите ответ своими словами", en: "Write your answer in your own words" },
  prev: { uz: "Oldingi", ru: "Назад", en: "Previous" },
  next: { uz: "Keyingi", ru: "Далее", en: "Next" },
  finish: { uz: "Yakunlash", ru: "Завершить", en: "Finish" },
  test_rules: { uz: "Test oynasidan chiqish va matn joylashtirish qayd etiladi. Bu jazo emas — o'qituvchiga yordam beradi.", ru: "Уход из окна теста и вставка текста фиксируются. Это не наказание — это помогает учителю.", en: "Leaving the test window and pasting text are recorded. This isn't a punishment — it helps your teacher." },
  followup_title: { uz: "Bitta qisqa savol", ru: "Один короткий вопрос", en: "One quick question" },
  followup_sub: { uz: "Javobingizni o'z so'zlaringiz bilan tushuntiring — bu tushunganingizni ko'rsatadi", ru: "Объясните ответ своими словами — это покажет, что вы поняли", en: "Explain your answer in your own words — it shows you understand" },
  fu_prompt_short: { uz: "Siz “{q}” savoliga “{a}” deb yozdingiz. Bunga qanday kelganingizni o'z so'zlaringiz bilan tushuntiring.", ru: "На вопрос «{q}» вы ответили «{a}». Объясните своими словами, как вы к этому пришли.", en: "For “{q}” you wrote “{a}”. Explain in your own words how you got there." },
  fu_prompt_mcq: { uz: "“{q}” savolida “{a}” ni tanladingiz. Nima uchun aynan shu javob?", ru: "В вопросе «{q}» вы выбрали «{a}». Почему именно этот ответ?", en: "In “{q}” you chose “{a}”. Why that answer?" },
  fu_placeholder: { uz: "Masalan: chunki…", ru: "Например: потому что…", en: "For example: because…" },
  test_finished: { uz: "Test yakunlandi!", ru: "Тест завершён!", en: "Test finished!" },
  test_finished_text: { uz: "Natija va tushuntirishlarni ko'rishingiz mumkin. Xatolar ustida AI repetitor bilan ishlang.", ru: "Можно посмотреть результат и объяснения. Разберите ошибки с AI-репетитором.", en: "You can see your result and the explanations. Work on your mistakes with the AI tutor." },
  practise_with_tutor: { uz: "Repetitor bilan mashq", ru: "Практика с репетитором", en: "Practise with the tutor" },

  // ---- assistant
  assistant_hello: { uz: "Salom! Men Maktab+ AI yordamchisiman", ru: "Здравствуйте! Я AI-помощник Maktab+", en: "Hi! I'm the Maktab+ AI assistant" },
  assistant_sub_student: { uz: "Mavzularni tushuntiradi, mashq beradi va reja tuzadi", ru: "Объясняет темы, даёт практику и составляет план", en: "Explains topics, gives practice and builds a study plan" },
  assistant_sub_parent: { uz: "Farzandingiz haqida tushunarli hisobot va maslahatlar", ru: "Понятный отчёт о ребёнке и советы", en: "Clear reports and advice about your child" },
  assistant_sub_teacher: { uz: "Sinf tahlili, dars g'oyalari va ota-onalarga xatlar", ru: "Анализ класса, идеи уроков и письма родителям", en: "Class analysis, lesson ideas and letters to parents" },
  assistant_sub_director: { uz: "Maktab tahlili va hisobotlar", ru: "Анализ школы и отчёты", en: "School analysis and reports" },
  assistant_intro_student: { uz: "Qaysi mavzu tushunarsiz? Men tushuntiraman, savol beraman va mashq qildiraman — lekin uy vazifangizni siz uchun bajarmayman 🙂", ru: "Какая тема непонятна? Я объясню, задам вопросы и дам практику — но домашку за вас не сделаю 🙂", en: "Which topic is unclear? I'll explain, ask questions and give you practice — but I won't do your homework for you 🙂" },
  assistant_intro_parent: { uz: "Farzandingizning baholari, davomati va uy vazifalari asosida savollaringizga javob beraman.", ru: "Отвечаю на вопросы по оценкам, посещаемости и ДЗ вашего ребёнка.", en: "I answer questions using your child's grades, attendance and homework." },
  assistant_intro_teacher: { uz: "Sinflaringiz ma'lumotlari asosida tahlil, g'oyalar va matnlar tayyorlayman.", ru: "Готовлю анализ, идеи и тексты по данным ваших классов.", en: "I prepare analysis, ideas and texts from your classes' data." },
  assistant_intro_director: { uz: "Butun maktab ma'lumotlari asosida hisobot va tavsiyalar beraman.", ru: "Даю отчёты и рекомендации по данным всей школы.", en: "I give reports and recommendations from whole-school data." },
  assistant_offline: { uz: "AI kaliti ulanmagan: yordamchi hozircha oflayn tahlil bilan javob beradi. To'liq suhbat uchun kalitni ulang.", ru: "AI-ключ не подключён: помощник отвечает офлайн-анализом. Для полноценного диалога подключите ключ.", en: "No AI key: the assistant answers with offline analysis for now. Connect a key for full conversations." },
  ask_anything: { uz: "Savolingizni yozing…", ru: "Напишите вопрос…", en: "Ask anything…" },
  assistant_privacy_default: { uz: "AI faqat sizga ruxsat berilgan ma'lumotlarni ko'radi.", ru: "AI видит только данные, доступные вам.", en: "The AI only sees data you are allowed to see." },
  assistant_privacy_director: { uz: "AI faqat maktab ma'lumotlarini ko'radi. Shaxsiy xulosalar — faqat taklif.", ru: "AI видит только данные школы. Выводы о людях — лишь предложения.", en: "The AI only sees school data. Conclusions about people are suggestions only." },
  q_student_weak: { uz: "Qaysi fanlarim zaif va nima qilishim kerak?", ru: "Какие предметы у меня слабые и что делать?", en: "Which subjects are weak and what should I do?" },
  q_student_explain: { uz: "Oxirgi kimyo mavzusini oddiy qilib tushuntir", ru: "Объясни простыми словами последнюю тему по химии", en: "Explain the last chemistry topic simply" },
  q_student_plan: { uz: "Chorak oxirigacha o'qish rejasini tuz", ru: "Составь план учёбы до конца четверти", en: "Make a study plan until the end of the quarter" },
  q_student_practice: { uz: "Matematikadan 5 ta mashq ber", ru: "Дай 5 упражнений по математике", en: "Give me 5 maths practice problems" },
  q_parent_report: { uz: "Farzandim haqida haftalik hisobot", ru: "Еженедельный отчёт о ребёнке", en: "Weekly report about my child" },
  q_parent_help: { uz: "Uyda qanday yordam bera olaman?", ru: "Как я могу помочь дома?", en: "How can I help at home?" },
  q_parent_attendance: { uz: "Davomatda muammo bormi?", ru: "Есть ли проблемы с посещаемостью?", en: "Are there any attendance problems?" },
  q_parent_talk: { uz: "O'qituvchi bilan nima haqida gaplashay?", ru: "О чём поговорить с учителем?", en: "What should I discuss with the teacher?" },
  q_teacher_class: { uz: "Sinfimning umumiy tahlili", ru: "Общий анализ моего класса", en: "Overall analysis of my class" },
  q_teacher_letter: { uz: "Xavf ostidagi o'quvchi ota-onasiga xat", ru: "Письмо родителю ученика в зоне риска", en: "A letter to the parent of a student at risk" },
  q_teacher_ideas: { uz: "Keyingi dars uchun 3 ta faol metod", ru: "3 активных метода для следующего урока", en: "3 active-learning ideas for my next lesson" },
  q_teacher_weak: { uz: "Zaif o'quvchilar uchun alohida topshiriqlar", ru: "Отдельные задания для слабых учеников", en: "Differentiated tasks for weaker students" },
  q_director_report: { uz: "Oylik maktab hisoboti", ru: "Ежемесячный отчёт школы", en: "Monthly school report" },
  q_director_risk: { uz: "Xavf ostidagi o'quvchilar va choralar", ru: "Ученики в зоне риска и меры", en: "Students at risk and actions" },
  q_director_attendance: { uz: "Davomat tahlili", ru: "Анализ посещаемости", en: "Attendance analysis" },
  q_director_actions: { uz: "Natijalarni oshirish uchun 5 ta qadam", ru: "5 шагов для улучшения результатов", en: "5 steps to improve results" },
  offline_report_title: { uz: "{name}: qisqa hisobot", ru: "{name}: краткий отчёт", en: "{name}: short report" },
  strong_subjects: { uz: "Kuchli fanlar", ru: "Сильные предметы", en: "Strong subjects" },
  needs_attention: { uz: "E'tibor kerak", ru: "Требуют внимания", en: "Needs attention" },
  advice: { uz: "Maslahat", ru: "Совет", en: "Advice" },
  advice_1: { uz: "{subject} fanidan har kuni 15–20 daqiqa takrorlash", ru: "Ежедневно 15–20 минут повторять «{subject}»", en: "Review {subject} for 15–20 minutes every day" },
  advice_2: { uz: "Uy vazifalarini kechqurun birga tekshirish", ru: "Вечером вместе проверять домашние задания", en: "Check homework together in the evening" },
  advice_3: { uz: "Haftalik test xatolarini AI repetitor bilan tahlil qilish", ru: "Разбирать ошибки еженедельного теста с AI-репетитором", en: "Go through weekly-test mistakes with the AI tutor" },
  offline_generic: { uz: "Bu savolga to'liq javob uchun AI kalitini ulang. Hozircha bosh sahifadagi AI kuzatuv ro'yxati va statistikadan foydalaning.", ru: "Для полного ответа подключите AI-ключ. Пока используйте AI-список внимания и статистику на главной.", en: "Connect an AI key for a full answer. Meanwhile, use the AI watchlist and statistics on the dashboard." },
  offline_result: { uz: "Oflayn tahlil (AI kalitisiz)", ru: "Офлайн-анализ (без AI-ключа)", en: "Offline analysis (no AI key)" },
  ai_offline_hint: { uz: "AI kaliti ulanmagan — oflayn versiya yaratiladi. To'liq AI uchun kalitni ulang.", ru: "AI-ключ не подключён — будет создана офлайн-версия. Для полного AI подключите ключ.", en: "No AI key — an offline version will be generated. Connect a key for full AI." },
  ai_needs_key: { uz: "Bu funksiya uchun AI kaliti kerak.", ru: "Для этой функции нужен AI-ключ.", en: "This feature needs an AI key." },
  ai_parent_letter: { uz: "Ota-onaga xat", ru: "Письмо родителю", en: "Letter to the parent" },
  ai_parent_letter_sub: { uz: "Ma'lumotlar asosida iliq va aniq xabar", ru: "Тёплое и конкретное сообщение на основе данных", en: "A warm, specific message based on the data" },

  // ---- AI errors
  aierr_noKey: { uz: "AI kaliti ulanmagan.", ru: "AI-ключ не подключён.", en: "No AI key connected." },
  aierr_auth: { uz: "API kalit noto'g'ri yoki ruxsat yo'q.", ru: "Неверный API-ключ или нет доступа.", en: "The API key is invalid or lacks permission." },
  aierr_rate: { uz: "So'rovlar ko'p — biroz kutib qayta urinib ko'ring.", ru: "Слишком много запросов — попробуйте чуть позже.", en: "Too many requests — please try again shortly." },
  aierr_network: { uz: "Internet aloqasi yo'q.", ru: "Нет соединения с интернетом.", en: "No internet connection." },
  aierr_refusal: { uz: "AI bu so'rovga javob bera olmadi.", ru: "AI не смог ответить на этот запрос.", en: "The AI could not answer this request." },
  aierr_parse: { uz: "AI javobini o'qib bo'lmadi, qayta urinib ko'ring.", ru: "Не удалось разобрать ответ AI, попробуйте ещё раз.", en: "Couldn't read the AI response — please try again." },
  aierr_other: { uz: "AI xatosi yuz berdi.", ru: "Произошла ошибка AI.", en: "An AI error occurred." },

  // ---- settings
  ai_connection: { uz: "AI ulanishi", ru: "Подключение AI", en: "AI connection" },
  ai_connection_sub: { uz: "Claude — tekshirish, repetitor, dars studiyasi va testlar uchun", ru: "Claude — проверка работ, репетитор, студия уроков и тесты", en: "Claude powers exam checking, the tutor, the lesson studio and tests" },
  ai_connected: { uz: "Ulangan", ru: "Подключено", en: "Connected" },
  ai_offline_mode: { uz: "Oflayn rejim", ru: "Офлайн-режим", en: "Offline mode" },
  model: { uz: "Model", ru: "Модель", en: "Model" },
  disconnect: { uz: "Uzish", ru: "Отключить", en: "Disconnect" },
  key_warning: { uz: "Faqat prototip uchun: kalit shu brauzerda saqlanadi va so'rovlar to'g'ridan-to'g'ri yuboriladi. Haqiqiy versiyada AI so'rovlari Maktab+ serveri orqali o'tadi va kalit hech kimga ko'rinmaydi.", ru: "Только для прототипа: ключ хранится в этом браузере, запросы идут напрямую. В рабочей версии запросы идут через сервер Maktab+, и ключ никому не виден.", en: "Prototype only: the key is stored in this browser and requests go directly from it. In production, AI requests go through the Maktab+ server and the key is never exposed." },
  ai_features_list: { uz: "Kalitsiz ham ishlaydi: “Kimdan so'rash”, xavf tahlili, mustaqillik tekshiruvi, oflayn imtihon tekshiruvi, virtual laboratoriya.", ru: "Без ключа работают: «Кого спросить», анализ риска, проверка самостоятельности, офлайн-проверка работ, виртуальная лаборатория.", en: "Works without a key: who to ask first, risk analysis, independent-work checks, offline exam checking, and the virtual lab." },
  appearance: { uz: "Ko'rinish", ru: "Внешний вид", en: "Appearance" },
  school_settings: { uz: "Maktab sozlamalari", ru: "Настройки школы", en: "School settings" },
  late_after_label: { uz: "Kechikish hisoblanadigan vaqt", ru: "Опоздание после", en: "Count as late after" },
  demo_data: { uz: "Demo ma'lumotlar", ru: "Демо-данные", en: "Demo data" },
  demo_data_sub: { uz: "Barcha o'zgarishlar shu brauzerda saqlanadi", ru: "Все изменения хранятся в этом браузере", en: "All changes are stored in this browser" },
  export_json: { uz: "JSON yuklab olish", ru: "Скачать JSON", en: "Download JSON" },
  reset_demo: { uz: "Demoni qayta tiklash", ru: "Сбросить демо", en: "Reset demo" },
  reset_confirm: { uz: "Barcha o'zgarishlar o'chiriladi. Davom etasizmi?", ru: "Все изменения будут удалены. Продолжить?", en: "All changes will be lost. Continue?" },
  reset_done: { uz: "Demo ma'lumotlar qayta tiklandi", ru: "Демо-данные сброшены", en: "Demo data has been reset" },
};
